# -*- coding: utf-8 -*-
"""Contrast Stretching

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VI-6Ngatr29BoStFg5uwVoDeBqOtXsmz
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load the image in grayscale
image = cv2.imread('/content/picture.jfif', cv2.IMREAD_GRAYSCALE)

# Get the minimum and maximum pixel values
min_val = np.min(image)
max_val = np.max(image)

# Apply Contrast Stretching
stretched_image = (image - min_val) * (255 / (max_val - min_val))
stretched_image = np.uint8(stretched_image)

# Display the original and stretched images
plt.figure(figsize=(10, 5))

# Original Image
plt.subplot(1, 2, 1)
plt.title('Original Image')
plt.imshow(image, cmap='gray')

# Stretched Image
plt.subplot(1, 2, 2)
plt.title('Contrast Stretched Image')
plt.imshow(stretched_image, cmap='gray')

plt.show()