# -*- coding: utf-8 -*-
"""Fourier Transform (FFT)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F-aFTdZHDXwZ4k9bS8YCAwvXZQfXLbil
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load the image in grayscale
image = cv2.imread('/content/image25.jpg', cv2.IMREAD_GRAYSCALE)

# Apply Fourier Transform
f_transform = np.fft.fft2(image)
f_shift = np.fft.fftshift(f_transform)

# Get the magnitude spectrum (log scale to enhance visibility)
magnitude_spectrum = 20 * np.log(np.abs(f_shift))

# Display the original image and its magnitude spectrum
plt.figure(figsize=(10, 5))

# Original Image
plt.subplot(1, 2, 1)
plt.title('Original Image')
plt.imshow(image, cmap='gray')

# Magnitude Spectrum
plt.subplot(1, 2, 2)
plt.title('Magnitude Spectrum (FFT)')
plt.imshow(magnitude_spectrum, cmap='gray')

plt.show()