# -*- coding: utf-8 -*-
"""Hough Transform

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F-aFTdZHDXwZ4k9bS8YCAwvXZQfXLbil
"""

import cv2
import pywt
import matplotlib.pyplot as plt

# Load the image in grayscale
image = cv2.imread('/content/image25.jpg', cv2.IMREAD_GRAYSCALE)

# Apply 2D Discrete Wavelet Transform (DWT)
coeffs2 = pywt.dwt2(image, 'haar')

# Extract the approximation and details coefficients
LL, (LH, HL, HH) = coeffs2

# Display the results
plt.figure(figsize=(10, 10))

# Approximation
plt.subplot(2, 2, 1)
plt.title('Approximation (LL)')
plt.imshow(LL, cmap='gray')

# Horizontal detail
plt.subplot(2, 2, 2)
plt.title('Horizontal Detail (LH)')
plt.imshow(LH, cmap='gray')

# Vertical detail
plt.subplot(2, 2, 3)
plt.title('Vertical Detail (HL)')
plt.imshow(HL, cmap='gray')

# Diagonal detail
plt.subplot(2, 2, 4)
plt.title('Diagonal Detail (HH)')
plt.imshow(HH, cmap='gray')

plt.show()

!pip install PyWavelets

import pywt
print("PyWavelets installed and ready to use!")