# -*- coding: utf-8 -*-
"""Canny Edge Detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XwZDOb-nI2O9NMhV_kPz1xx7TBtgBf3_
"""

import cv2
import matplotlib.pyplot as plt

# Load the image in grayscale
image = cv2.imread('/content/345.jpeg', cv2.IMREAD_GRAYSCALE)

# Apply Canny Edge Detection
edges = cv2.Canny(image, 100, 200)

# Display original and edge-detected images
plt.figure(figsize=(10, 5))

# Original Image
plt.subplot(1, 2, 1)
plt.title('Original Image')
plt.imshow(image, cmap='gray')

# Canny Edge Detection
plt.subplot(1, 2, 2)
plt.title('Canny Edge Detection')
plt.imshow(edges, cmap='gray')

plt.show()