# -*- coding: utf-8 -*-
"""Thresholding

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XwZDOb-nI2O9NMhV_kPz1xx7TBtgBf3_
"""

import cv2
import matplotlib.pyplot as plt

# Load the image in grayscale
image = cv2.imread('/content/345.jpeg', cv2.IMREAD_GRAYSCALE)

# Apply global thresholding
_, thresholded_image = cv2.threshold(image, 127, 255, cv2.THRESH_BINARY)

# Display original and thresholded images
plt.figure(figsize=(10, 5))

# Original Image
plt.subplot(1, 2, 1)
plt.title('Original Image')
plt.imshow(image, cmap='gray')

# Thresholded Image
plt.subplot(1, 2, 2)
plt.title('Thresholded Image')
plt.imshow(thresholded_image, cmap='gray')

plt.show()